version: 0.1.{build}

platform:
  - x86

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 4.4.7 x86
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist

artifacts:
  - path: 'dist\win-ia32\*.exe'
  

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
