version: 0.1.{build}

platform:
  - x86

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6.8.1 x86
  - git reset --hard HEAD
  - npm install npm -g
  - npm install -g json 
  - npm install electron-builder
  - npm install
  - npm prune

build_script:
  - ps: env
  - node --version
  - npm --version
  - cmd: json -I -f C:\projects\electrontest\package.json -e 'this.version=process.env.APPVEYOR_BUILD_VERSION'
  - ps: get-content package.json
  - npm run dist

artifacts:
  - path: 'dist\win-ia32\*.exe'
    name: setup
  

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off
